/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_login (void);
GtkWidget* create_window_espace_admin (void);
GtkWidget* create_window_espace_entraineur (void);
GtkWidget* create_window_espace_membres (void);
GtkWidget* create_window_ajouter_centre (void);
GtkWidget* create_window_modifier_centre (void);
GtkWidget* create_window_ajouter_entraineur (void);
GtkWidget* create_window_modifier_entraineur (void);
GtkWidget* create_window_ajouter_membre (void);
GtkWidget* create_window_modifier_membre (void);
GtkWidget* create_window_ajouter_equipement (void);
GtkWidget* create_window_modifier_equipement (void);
GtkWidget* create_window_ajouter_event (void);
GtkWidget* create_window_modifier_event (void);
GtkWidget* create_window_ajouter_cours (void);
GtkWidget* create_window_modifier_cours (void);
GtkWidget* create_window_inscri_centre_trainer (void);
GtkWidget* create_window_mesinscri_trainer (void);
GtkWidget* create_window_mesinscri_mod_role_trainer (void);
GtkWidget* create_window_mescours_trainer (void);
GtkWidget* create_window_mescours_membre (void);
GtkWidget* create_window_mesentrainneurs_membre (void);
GtkWidget* create_window_mesevent_membre (void);
GtkWidget* create_window_equip_dispo_trainer (void);
GtkWidget* create_window_depassement_nombre (void);
GtkWidget* create_window_equip_reserve_trainer (void);
