/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

// Global variables
char USER_FILE_PATH[256] = "./src/database/user.txt";
char COURS_FILE_PATH[256] = "./src/database/cours.txt";
char EQUIPEMENT_FILE_PATH[256] = "./src/database/equipements.txt";
char CENTRE_FILE_PATH[256] = "./src/database/centres.txt";
char ENTRAINEUR_FILE_PATH[256] = "./src/database/entraineurs.txt";
char MEMBRE_FILE_PATH[256] = "./src/database/membres.txt";
char EVENT_FILE_PATH[256] = "./src/database/events.txt";
char INSCRIPTION_ENTRAINEUR_FILE_PATH[256] = "./src/database/inscriptionentraineur.txt";
char INSCRIPTION_MEMBRE_FILE_PATH[256] = "./src/database/inscriptionmembre.txt";
char ENTRAINEUR_PRIVE_FILE_PATH[256] = "./src/database/entraineurprive.txt";

int current_membre_id = -1;
int current_trainer_id = -1;
char current_membre_id_str[50] = "";
char current_trainer_id_str[50] = "";

// Global window pointers
GtkWidget *window_login = NULL;
GtkWidget *window_espace_admin = NULL;
GtkWidget *window_espace_entraineur = NULL;
GtkWidget *window_espace_membres = NULL;

int
main (int argc, char *argv[])
{
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("./src/pixmaps");

  /*
   * Only create and show the login window initially
   */
  window_login = create_window_login ();
  gtk_widget_show (window_login);

  gtk_main ();
  return 0;
}
